<?php
    //This code is for Codeigniter, but will work similarly in other frameworks or straight PHP
    //This is the function that will be called when there is an LTI Post to the page
	public function index() {
        $this->load->model('lti_login_model');

    		//first check to make sure there is a proper oAuth signature
    		if (!$this->lti_login_model->requestIsSigned()) {  
    			show_error("Invalid call", 403);
    			return false;
    		}
    		
    		// see if this is a valid request with a valid key
    		if ($ltiInfo = $this->lti_login_model->validateLtiAccess()) {
    			//check signature generated by secret
    			if (!$this->lti_login_model->verifySignature($ltiInfo['consumer_secret'])) {  
    				show_error("Invalid call (invalid signature)", 403);
    				return false;
    			}
    			
    		} else {
    			//key must be wrong
    			show_error("Invalid call (unknown requester)", 403);
    			return false;
    		}
    		
    	//Since we've made it this far, everything must be good.  So let's get the user's info			
		$userInfo = $this->lti_login_model->getLtiUserInfo($ltiInfo['consumer_id']);
	
